### ISSUE TITLE
[FEATURE] Pull licenses from xml file

### ISSUE THREAD

**Issue by snorkel123** [franmontiel/AttributionPresenter#2]
This feature presents in [PSDev/LicensesDialog](https://github.com/PSDev/LicensesDialog)

Sample file: https://github.com/PSDev/LicensesDialog/tree/master/sample/res/raw

**Comment by franmontiel** [comment]
Thanks for your suggestion but I want to maintain this library quite simple, just a little help for creating a license view so this probably won't be added.
