### ISSUE TITLE
Visibility of class AttributionAdapter

### ISSUE THREAD

**Issue by nbossard** [franmontiel/AttributionPresenter#4]
Class AttributionAdapter has a package visibility, so not accessible from my project, here is the error I get in my kotlin project : 

Type AttributionAdapter! is inaccessible in this context due to: public/*package*/ open class AttributionAdapter : BaseAdapter defined in com.franmontiel.attributionpresenter |  
-- | --

**Comment by franmontiel** [comment]
Version 1.0.1 released fixing this issue
